In [61]:
import pandas as pd

excel_file_name = 'c:/myPyCode/data/play_typing2.xlsx'

df = pd.read_excel(excel_file_name, index_col = '학생').T

df

학생,김승규,김정훈,마가진,문지현,신준호,신지환,오병훈,오창환,윤경주,윤혜수,...,이용주,이유록,임건우,장은진,조철호,지승배,최종준,편효범,황영범,황정현
2020-10-05 00:00:00,336,102,5,230,278,258,156,157,151,123,...,177,193,175,234,225,199,89,221,156,182
2020-10-05 00:00:00.1,100,99,62,100,100,100,99,100,99,99,...,99,99,99,99,99,98,99,97,99,98
2020-10-06 00:00:00,298,120,35,229,242,결석,161,167,167,157,...,178,207,188,257,264,232,103,246,88,175
2020-10-06 00:00:00.1,99,99,99,99,100,결석,99,100,100,99,...,99,99,99,98,99,97,99,97,98,98
2020-10-07 00:00:00,387,132,87,229,256,269,171,163,165,150,...,190,204,179,246,268,237,112,238,117,195
2020-10-07 00:00:00.1,100,100,98,99,99,100,99,100,NaN,100,...,99,99,99,99,99,98,99,99,97,100
2020-10-12 00:00:00,317,150,74,229,261,272,169,173,202(병결),172,...,186,204,병가,249,241,228,118,228,143,205
2020-10-12 00:00:00.1,99,100,95,100,100,100,99,100,99(병결),99,...,100,100,병가,99,100,98,100,99,99,99
2020-10-13 00:00:00,313,125,49,227,247,241,161,163,170,119,...,158,218,지각,256,212,229,103,208,125,200
2020-10-13 00:00:00.1,99,99,80,99,99,100,98,99,100,100,...,99,99,지각,100,100,98,99,99,99,100
2020-10-14 00:00:00,310,NaN,56,221,249,259,174,173,169,136,...,168,209,190,254,236,236,120,222,135,197
2020-10-14 00:00:00.1,100,NaN,99,99,99,100,98,100,99,99,...,99,100,99,99,99,98,99,99,98,99
2020-10-15 00:00:00,334,143,75,220,260,262,183,170,171,137,...,186,220,190,250,255,243,103,237,146,210
2020-10-15 00:00:00.1,100,99,99,99,99,100,99,99,99,100,...,100,99,97,99,99,98,99,99,99,99
2020-10-16 00:00:00,324,143,73,222,250,274,169,181,163,143,...,189,225,192,261,240,225,114,220,144,201
2020-10-16 00:00:00.1,100,99,98,99,100,99,99,99,99,100,...,99,99,99,99,99,97,99,99,100,99
2020-10-19 00:00:00,327,152,72,235,261,결석,186,지각,185,158,...,184,214,237,259,269,224,124,231,결석,209
2020-10-19 00:00:00.1,100,99,91,99,99,결석,99,지각,99,99,...,99,99,99,99,99,97,99,99,결석,99
2020-10-20 00:00:00,308,161,93,220,278,257,182,180,병결(167),167,...,184,230,221,242,274,230,144,238,153,196
2020-10-20 00:00:00.1,99,100,99,99,99,99,99,99,병결(99),100,...,100,99,100,100,99,98,100,99,99,99
2020-10-21 00:00:00,311,148,100,235,243,269,192,결석,191,155,...,192,232,결석,259,261,239,114,237,150,217
2020-10-21 00:00:00.1,100,99,99,99,99,100,99,결석,100,100,...,100,98,결석,99,99,98,99,99,100,100
2020-10-22 00:00:00,369,171,85,236,249,268,200,결석,197,166,...,204,227,243,262,260,244,111,239,165,214
2020-10-22 00:00:00.1,99,99,99,99,99,100,99,결석,99,100,...,99,100,99,100,100,97,100,99,99,99
2020-10-23 00:00:00,318,166,100,235,260,281,187,결석,212,177,...,211,238,NaN,270,263,231,103,257,175,219
2020-10-23 00:00:00.1,100,99,99,99,99,99,98,결석,99,NaN,...,99,99,NaN,99,100,97,99,99,99,99
2020-10-26 00:00:00,323,160,98,220,249,결석,188,결석,175,156,...,174,230,결석,263,238,238,99,216,148,186
2020-10-26 00:00:00.1,100,99,99,99,99,결석,98,결석,99,99,...,98,99,결석,99,100,97,99,99,99,100
2020-10-27 00:00:00,342,결석,97,229,247,258,187,결석,174,183,...,195,231,192,266,257,248,120,243,165,212
2020-10-27 00:00:00.1,99,결석,100,99,100,99,99,결석,99,99,...,99,99,99,100,99,97,99,99,99,99
2020-10-28 00:00:00,348,167,90,245,241,260,188,NaN,188,158,...,204,211,201,270,256,232,106,226,167,223
2020-10-28 00:00:00.1,100,99,98,99,99,99,99,NaN,99,100,...,99,99,99,99,100,97,99,99,99,99

In [63]:
day_tp = df[::2]
day_tp

학생,김승규,김정훈,마가진,문지현,신준호,신지환,오병훈,오창환,윤경주,윤혜수,...,이용주,이유록,임건우,장은진,조철호,지승배,최종준,편효범,황영범,황정현
2020-10-05 00:00:00,336,102,5,230,278,258,156,157,151,123,...,177,193,175,234,225,199,89,221,156,182
2020-10-06 00:00:00,298,120,35,229,242,결석,161,167,167,157,...,178,207,188,257,264,232,103,246,88,175
2020-10-07 00:00:00,387,132,87,229,256,269,171,163,165,150,...,190,204,179,246,268,237,112,238,117,195
2020-10-12 00:00:00,317,150,74,229,261,272,169,173,202(병결),172,...,186,204,병가,249,241,228,118,228,143,205
2020-10-13 00:00:00,313,125,49,227,247,241,161,163,170,119,...,158,218,지각,256,212,229,103,208,125,200
2020-10-14 00:00:00,310,NaN,56,221,249,259,174,173,169,136,...,168,209,190,254,236,236,120,222,135,197
2020-10-15 00:00:00,334,143,75,220,260,262,183,170,171,137,...,186,220,190,250,255,243,103,237,146,210
2020-10-16 00:00:00,324,143,73,222,250,274,169,181,163,143,...,189,225,192,261,240,225,114,220,144,201
2020-10-19 00:00:00,327,152,72,235,261,결석,186,지각,185,158,...,184,214,237,259,269,224,124,231,결석,209
2020-10-20 00:00:00,308,161,93,220,278,257,182,180,병결(167),167,...,184,230,221,242,274,230,144,238,153,196
2020-10-21 00:00:00,311,148,100,235,243,269,192,결석,191,155,...,192,232,결석,259,261,239,114,237,150,217
2020-10-22 00:00:00,369,171,85,236,249,268,200,결석,197,166,...,204,227,243,262,260,244,111,239,165,214
2020-10-23 00:00:00,318,166,100,235,260,281,187,결석,212,177,...,211,238,NaN,270,263,231,103,257,175,219
2020-10-26 00:00:00,323,160,98,220,249,결석,188,결석,175,156,...,174,230,결석,263,238,238,99,216,148,186
2020-10-27 00:00:00,342,결석,97,229,247,258,187,결석,174,183,...,195,231,192,266,257,248,120,243,165,212
2020-10-28 00:00:00,348,167,90,245,241,260,188,NaN,188,158,...,204,211,201,270,256,232,106,226,167,223

In [64]:
name_day_tp = day_tp['조철호']
name_day_tp

# dfname = pd.DataFrame(name_day_tp, columns = ['Date', '타이핑'])
# dfname

2020-10-05    225
2020-10-06    264
2020-10-07    268
2020-10-12    241
2020-10-13    212
2020-10-14    236
2020-10-15    255
2020-10-16    240
2020-10-19    269
2020-10-20    274
2020-10-21    261
2020-10-22    260
2020-10-23    263
2020-10-26    238
2020-10-27    257
2020-10-28    256
Name: 조철호, dtype: object

In [65]:
dftvalue = name_day_tp.values.tolist()
dftvalue

[225,
 264,
 268,
 241,
 212,
 236.0,
 255,
 240,
 269,
 274,
 261,
 260,
 263,
 238,
 257,
 256.0]

In [72]:
index_label = ['1day', '2day', '3day', '4day', '5day', '6day', '7day', '8day', '9day', '10day', '11day', '12day', '13day', '14day', '15day', '16day']


totaldata_tp = {'타이핑' : dfvalue}

dfttotal = pd.DataFrame(totaldata_tp, index = index_label, columns = ['타이핑'])
dfttotal

         타이핑
1day   225.0
2day   264.0
3day   268.0
4day   241.0
5day   212.0
6day   236.0
7day   255.0
8day   240.0
9day   269.0
10day  274.0
11day  261.0
12day  260.0
13day  263.0
14day  238.0
15day  257.0
16day  256.0

In [67]:
day_ex = df[1::2]
day_ex

학생,김승규,김정훈,마가진,문지현,신준호,신지환,오병훈,오창환,윤경주,윤혜수,...,이용주,이유록,임건우,장은진,조철호,지승배,최종준,편효범,황영범,황정현
2020-10-05 00:00:00.1,100,99,62,100,100,100,99,100,99,99,...,99,99,99,99,99,98,99,97,99,98
2020-10-06 00:00:00.1,99,99,99,99,100,결석,99,100,100,99,...,99,99,99,98,99,97,99,97,98,98
2020-10-07 00:00:00.1,100,100,98,99,99,100,99,100,NaN,100,...,99,99,99,99,99,98,99,99,97,100
2020-10-12 00:00:00.1,99,100,95,100,100,100,99,100,99(병결),99,...,100,100,병가,99,100,98,100,99,99,99
2020-10-13 00:00:00.1,99,99,80,99,99,100,98,99,100,100,...,99,99,지각,100,100,98,99,99,99,100
2020-10-14 00:00:00.1,100,NaN,99,99,99,100,98,100,99,99,...,99,100,99,99,99,98,99,99,98,99
2020-10-15 00:00:00.1,100,99,99,99,99,100,99,99,99,100,...,100,99,97,99,99,98,99,99,99,99
2020-10-16 00:00:00.1,100,99,98,99,100,99,99,99,99,100,...,99,99,99,99,99,97,99,99,100,99
2020-10-19 00:00:00.1,100,99,91,99,99,결석,99,지각,99,99,...,99,99,99,99,99,97,99,99,결석,99
2020-10-20 00:00:00.1,99,100,99,99,99,99,99,99,병결(99),100,...,100,99,100,100,99,98,100,99,99,99
2020-10-21 00:00:00.1,100,99,99,99,99,100,99,결석,100,100,...,100,98,결석,99,99,98,99,99,100,100
2020-10-22 00:00:00.1,99,99,99,99,99,100,99,결석,99,100,...,99,100,99,100,100,97,100,99,99,99
2020-10-23 00:00:00.1,100,99,99,99,99,99,98,결석,99,NaN,...,99,99,NaN,99,100,97,99,99,99,99
2020-10-26 00:00:00.1,100,99,99,99,99,결석,98,결석,99,99,...,98,99,결석,99,100,97,99,99,99,100
2020-10-27 00:00:00.1,99,결석,100,99,100,99,99,결석,99,99,...,99,99,99,100,99,97,99,99,99,99
2020-10-28 00:00:00.1,100,99,98,99,99,99,99,NaN,99,100,...,99,99,99,99,100,97,99,99,99,99

In [68]:
name_day_ex = day_ex['조철호']
name_day_ex

2020-10-05 00:00:00.1     99
2020-10-06 00:00:00.1     99
2020-10-07 00:00:00.1     99
2020-10-12 00:00:00.1    100
2020-10-13 00:00:00.1    100
2020-10-14 00:00:00.1     99
2020-10-15 00:00:00.1     99
2020-10-16 00:00:00.1     99
2020-10-19 00:00:00.1     99
2020-10-20 00:00:00.1     99
2020-10-21 00:00:00.1     99
2020-10-22 00:00:00.1    100
2020-10-23 00:00:00.1    100
2020-10-26 00:00:00.1    100
2020-10-27 00:00:00.1     99
2020-10-28 00:00:00.1    100
Name: 조철호, dtype: object

In [69]:
dfevalue = name_day_ex.values.tolist()
dfevalue

[99, 99, 99.0, 100, 100, 99.0, 99, 99, 99, 99, 99, 100, 100, 100, 99, 100.0]

In [73]:
totaldata_ex = {'정확도' : dfevalue}

dfetotal = pd.DataFrame(totaldata_ex, index=index_label, columns = ['정확도'])
dfetotal

         정확도
1day    99.0
2day    99.0
3day    99.0
4day   100.0
5day   100.0
6day    99.0
7day    99.0
8day    99.0
9day    99.0
10day   99.0
11day   99.0
12day  100.0
13day  100.0
14day  100.0
15day   99.0
16day  100.0

In [75]:
total = dfttotal.join(dfetotal)
total

         타이핑    정확도
1day   225.0   99.0
2day   264.0   99.0
3day   268.0   99.0
4day   241.0  100.0
5day   212.0  100.0
6day   236.0   99.0
7day   255.0   99.0
8day   240.0   99.0
9day   269.0   99.0
10day  274.0   99.0
11day  261.0   99.0
12day  260.0  100.0
13day  263.0  100.0
14day  238.0  100.0
15day  257.0   99.0
16day  256.0  100.0

In [76]:
total[(total['타이핑'] >= 250) & (total['정확도'] >= 100)]

         타이핑    정확도
12day  260.0  100.0
13day  263.0  100.0
16day  256.0  100.0